//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeltaClient.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/Delta.DeltaDBManager.CarNS")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BurnedLitersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KilometersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlateNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BurnedLiters {
            get {
                return this.BurnedLitersField;
            }
            set {
                if ((this.BurnedLitersField.Equals(value) != true)) {
                    this.BurnedLitersField = value;
                    this.RaisePropertyChanged("BurnedLiters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kilometers {
            get {
                return this.KilometersField;
            }
            set {
                if ((this.KilometersField.Equals(value) != true)) {
                    this.KilometersField = value;
                    this.RaisePropertyChanged("Kilometers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make {
            get {
                return this.MakeField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeField, value) != true)) {
                    this.MakeField = value;
                    this.RaisePropertyChanged("Make");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlateNumber {
            get {
                return this.PlateNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PlateNumberField, value) != true)) {
                    this.PlateNumberField = value;
                    this.RaisePropertyChanged("PlateNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Delta.DeltaManager.Utils")]
    [System.SerializableAttribute()]
    public partial class ManagerFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/Delta.DeltaDBManager.ServiceNS")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KilometersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeltaClient.Service.Car ServicedCarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float TotalSpentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Kilometers {
            get {
                return this.KilometersField;
            }
            set {
                if ((this.KilometersField.Equals(value) != true)) {
                    this.KilometersField = value;
                    this.RaisePropertyChanged("Kilometers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeltaClient.Service.Car ServicedCar {
            get {
                return this.ServicedCarField;
            }
            set {
                if ((object.ReferenceEquals(this.ServicedCarField, value) != true)) {
                    this.ServicedCarField = value;
                    this.RaisePropertyChanged("ServicedCar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float TotalSpent {
            get {
                return this.TotalSpentField;
            }
            set {
                if ((this.TotalSpentField.Equals(value) != true)) {
                    this.TotalSpentField = value;
                    this.RaisePropertyChanged("TotalSpent");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Delta.DeltaManager.ServiceNS", ConfigurationName="Service.IServiceManager")]
    public interface IServiceManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/addCarService", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/addCarServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeltaClient.Service.ManagerFault), Action="Delta.DeltaManager.ServiceNS/IServiceManager/addCarServiceManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Delta.DeltaManager.Utils")]
        bool addCarService(int Kilometers, DeltaClient.Service.Car ServicedCar, float TotalSpent, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/addCarService", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/addCarServiceResponse")]
        System.Threading.Tasks.Task<bool> addCarServiceAsync(int Kilometers, DeltaClient.Service.Car ServicedCar, float TotalSpent, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/GetCarServicesForCar", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/GetCarServicesForCarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeltaClient.Service.ManagerFault), Action="Delta.DeltaManager.ServiceNS/IServiceManager/GetCarServicesForCarManagerFaultFaul" +
            "t", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Delta.DeltaManager.Utils")]
        DeltaClient.Service.Service[] GetCarServicesForCar(string Plate, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/GetCarServicesForCar", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/GetCarServicesForCarResponse")]
        System.Threading.Tasks.Task<DeltaClient.Service.Service[]> GetCarServicesForCarAsync(string Plate, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/DeleteService", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/DeleteServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeltaClient.Service.ManagerFault), Action="Delta.DeltaManager.ServiceNS/IServiceManager/DeleteServiceManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Delta.DeltaManager.Utils")]
        bool DeleteService(int ID, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/DeleteService", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/DeleteServiceResponse")]
        System.Threading.Tasks.Task<bool> DeleteServiceAsync(int ID, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/GetServiceByID", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/GetServiceByIDResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeltaClient.Service.ManagerFault), Action="Delta.DeltaManager.ServiceNS/IServiceManager/GetServiceByIDManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Delta.DeltaManager.Utils")]
        DeltaClient.Service.Service GetServiceByID(int ID, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/GetServiceByID", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/GetServiceByIDResponse")]
        System.Threading.Tasks.Task<DeltaClient.Service.Service> GetServiceByIDAsync(int ID, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/UpdateService", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/UpdateServiceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DeltaClient.Service.ManagerFault), Action="Delta.DeltaManager.ServiceNS/IServiceManager/UpdateServiceManagerFaultFault", Name="ManagerFault", Namespace="http://schemas.datacontract.org/2004/07/Delta.DeltaManager.Utils")]
        bool UpdateService(DeltaClient.Service.Service service, string Email, string MD5PassHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="Delta.DeltaManager.ServiceNS/IServiceManager/UpdateService", ReplyAction="Delta.DeltaManager.ServiceNS/IServiceManager/UpdateServiceResponse")]
        System.Threading.Tasks.Task<bool> UpdateServiceAsync(DeltaClient.Service.Service service, string Email, string MD5PassHash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceManagerChannel : DeltaClient.Service.IServiceManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceManagerClient : System.ServiceModel.ClientBase<DeltaClient.Service.IServiceManager>, DeltaClient.Service.IServiceManager {
        
        public ServiceManagerClient() {
        }
        
        public ServiceManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool addCarService(int Kilometers, DeltaClient.Service.Car ServicedCar, float TotalSpent, string Email, string MD5PassHash) {
            return base.Channel.addCarService(Kilometers, ServicedCar, TotalSpent, Email, MD5PassHash);
        }
        
        public System.Threading.Tasks.Task<bool> addCarServiceAsync(int Kilometers, DeltaClient.Service.Car ServicedCar, float TotalSpent, string Email, string MD5PassHash) {
            return base.Channel.addCarServiceAsync(Kilometers, ServicedCar, TotalSpent, Email, MD5PassHash);
        }
        
        public DeltaClient.Service.Service[] GetCarServicesForCar(string Plate, string Email, string MD5PassHash) {
            return base.Channel.GetCarServicesForCar(Plate, Email, MD5PassHash);
        }
        
        public System.Threading.Tasks.Task<DeltaClient.Service.Service[]> GetCarServicesForCarAsync(string Plate, string Email, string MD5PassHash) {
            return base.Channel.GetCarServicesForCarAsync(Plate, Email, MD5PassHash);
        }
        
        public bool DeleteService(int ID, string Email, string MD5PassHash) {
            return base.Channel.DeleteService(ID, Email, MD5PassHash);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteServiceAsync(int ID, string Email, string MD5PassHash) {
            return base.Channel.DeleteServiceAsync(ID, Email, MD5PassHash);
        }
        
        public DeltaClient.Service.Service GetServiceByID(int ID, string Email, string MD5PassHash) {
            return base.Channel.GetServiceByID(ID, Email, MD5PassHash);
        }
        
        public System.Threading.Tasks.Task<DeltaClient.Service.Service> GetServiceByIDAsync(int ID, string Email, string MD5PassHash) {
            return base.Channel.GetServiceByIDAsync(ID, Email, MD5PassHash);
        }
        
        public bool UpdateService(DeltaClient.Service.Service service, string Email, string MD5PassHash) {
            return base.Channel.UpdateService(service, Email, MD5PassHash);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateServiceAsync(DeltaClient.Service.Service service, string Email, string MD5PassHash) {
            return base.Channel.UpdateServiceAsync(service, Email, MD5PassHash);
        }
    }
}
